MAIN_CATEGORIES = {
    "Женщинам": "woman",
    "Обувь": "shoes",
    "Детям": "kids",
    "Мужчинам": "man",
    "Дом": "house",
    "Электроника": "elect",
    "Бытовая техника": "technique",
    "Спорт": "sport",
    "Для ремонта": "repair",
    "Сад и дача": "village",
    "Продукты": "food",
    "Аксессуары": "accessories",
    "Игрушки": "toys",
    "Мебель": "furniture",
    "Автотовары": "avto",
    "Ювелирные изделия": "jewelry",
    "Красота": "beauty",
    "Здоровье": "health"
}
